#!/bin/bash
# =============================================================
# Scroff Server - One-click Deploy (Ubuntu 22.04 / 24.04)
# Usage: sudo bash deploy-ubuntu.sh
# =============================================================
# 配置说明：
#   - 公共配置 application.yml 随 jar 部署（提交到 Git）
#   - 敏感配置写到 /opt/scroff-server/scroff-server.env
#     （不提交到 Git，部署脚本自动生成）
#   - systemd 通过 EnvironmentFile 注入密码
# =============================================================
set -e

SCROFF_USER=scroff
SCROFF_HOME=/opt/scroff-server
SCROFF_PORT=8080
DB_NAME=scroff
DB_USER=scroff
DB_PASS="${SCROFF_DB_PASS:-scroff_pwd}"   # 可通过环境变量覆盖

echo "==> 1/8 Installing system packages"
apt-get update
apt-get install -y openjdk-17-jdk-headless mariadb-server adb curl

echo "==> 2/8 Creating service user"
id -u $SCROFF_USER >/dev/null 2>&1 || useradd -r -s /bin/false $SCROFF_USER

echo "==> 3/8 Creating database"
systemctl enable --now mariadb
mysql -uroot <<EOF
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOF

echo "==> 4/8 Deploying jar and config"
mkdir -p $SCROFF_HOME
cp scroff-server.jar $SCROFF_HOME/
cp application.yml $SCROFF_HOME/ 2>/dev/null || true

# Generate scroff-server.env (NOT committed to git, contains DB password)
cat > $SCROFF_HOME/scroff-server.env <<ENV
# Scroff Server - runtime environment (auto-generated by deploy-ubuntu.sh)
# Contains sensitive values. Do NOT commit this file to Git.
SPRING_PROFILES_ACTIVE=prod
SPRING_DATASOURCE_PASSWORD=${DB_PASS}
ENV
chmod 600 $SCROFF_HOME/scroff-server.env
chown $SCROFF_USER:$SCROFF_USER $SCROFF_HOME/scroff-server.env

chown -R $SCROFF_USER:$SCROFF_USER $SCROFF_HOME

echo "==> 5/8 Deploying systemd unit"
cat > /etc/systemd/system/scroff-server.service <<UNIT
[Unit]
Description=Scroff Server - ADB-based screen controller
After=network.target mariadb.service
Wants=mariadb.service

[Service]
Type=simple
User=$SCROFF_USER
WorkingDirectory=$SCROFF_HOME
EnvironmentFile=$SCROFF_HOME/scroff-server.env
ExecStart=/usr/bin/java -jar $SCROFF_HOME/scroff-server.jar
Restart=always
RestartSec=5
StandardOutput=append:/var/log/scroff-server.log
StandardError=append:/var/log/scroff-server.err.log
Environment=JAVA_OPTS="-Xms256m -Xmx512m"

# Security hardening (optional, uncomment after testing)
# NoNewPrivileges=true
# ProtectSystem=strict
# ReadWritePaths=$SCROFF_HOME /var/log

[Install]
WantedBy=multi-user.target
UNIT

echo "==> 6/8 Starting service"
systemctl daemon-reload
systemctl enable --now scroff-server
sleep 3
systemctl status scroff-server --no-pager

echo "==> 7/8 Verifying"
curl -fsS http://127.0.0.1:$SCROFF_PORT/ -o /dev/null && echo "Web OK" || echo "Web unreachable"

echo "==> 8/8 Starting adb daemon"
adb start-server 2>/dev/null || true

cat <<EOF

============================================================
 Deploy complete!

 URL:      http://<server-ip>:$SCROFF_PORT
 DB:       $DB_NAME (user: $DB_USER / pass: stored in scroff-server.env)
 Logs:     /var/log/scroff-server.log
 Secrets:  $SCROFF_HOME/scroff-server.env   (NOT in Git)

 Service management:
   sudo systemctl status  scroff-server
   sudo systemctl restart scroff-server
   sudo systemctl stop    scroff-server

 If you need to rotate the DB password later:
   1. sudo nano $SCROFF_HOME/scroff-server.env   # update SPRING_DATASOURCE_PASSWORD
   2. sudo mysql -uroot -e "ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY 'new_pass';"
   3. sudo systemctl restart scroff-server

 Next step - connect call-number machines via USB once:
   adb tcpip 5555
   adb devices          # note the device IP
 Then add IP:5555 in the web UI under Devices.
============================================================
EOF
